### ISSUE TITLE
Erro no job deploy_radar

### ISSUE THREAD

**Issue by leonardofl** [radar-parlamentar/implantacao#11]
Parece q o prompt ficou parado esperando a senha no "sudo chef-solo -c implantacao/solo.rb"...
Oq é estranho, pq tô na amazon e lá o sudo é sem senha.
Mas a treta deve ser pq tô rodando com o user do job, q não deve ter sudo...
Agora voltamos ao dilema de tentar rodar o job do jenkins com o usuário do SO (com o qual testávamos a receita).
Qd deu essa treta antes, eu resolvi deixando o usuário jenkins como dono do virtual env.
Mas dessa vez não sei se essa abordagem rola... parece q é melhor alterar o usuário do jenkins mesmo...

Log do jenkins:

```
Started by upstream project "build_radar" build number 1
originally caused by:
 Started by an SCM change
Building in workspace /var/lib/jenkins/jobs/deploy_radar/workspace
[workspace] $ /bin/sh -xe /tmp/hudson8833733523908850774.sh
+ bash -l -c source /home/ubuntu/venv_jenkins/bin/activate && fab -f /home/ubuntu/fabfile.py localhost deploy 
/usr/lib/python2.7/getpass.py:83: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
[localhost] Login password for 'ubuntu': [localhost] Executing task 'deploy'
[localhost] sudo: chef-solo -c implantacao/solo.rb
Traceback (most recent call last):
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/main.py", line 743, in main
    *args, **kwargs
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/tasks.py", line 384, in execute
    multiprocessing
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/tasks.py", line 274, in _execute
    return task.run(*args, **kwargs)
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/tasks.py", line 174, in run
    return self.wrapped(*args, **kwargs)
  File "/home/ubuntu/fabfile.py", line 16, in deploy
    sudo('chef-solo -c implantacao/solo.rb')
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/network.py", line 647, in host_prompting_wrapper
    return func(*args, **kwargs)
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/operations.py", line 1107, in sudo
    stderr=stderr, timeout=timeout, shell_escape=shell_escape,
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/operations.py", line 921, in _run_command
    channel=default_channel(), command=wrapped_command, pty=pty,
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/state.py", line 397, in default_channel
    chan = _open_session()
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/state.py", line 389, in _open_session
    return connections[env.host_string].get_transport().open_session()
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/network.py", line 159, in __getitem__
    self.connect(key)
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/network.py", line 151, in connect
    user, host, port, cache=self, seek_gateway=seek_gateway)
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/network.py", line 531, in connect
    password = prompt_for_password(text)
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/network.py", line 612, in prompt_for_password
    new_password = _password_prompt(password_prompt, stream)
  File "/home/ubuntu/venv_jenkins/local/lib/python2.7/site-packages/fabric/network.py", line 584, in _password_prompt
    return getpass.getpass(prompt.encode('ascii', 'ignore'), stream)
  File "/usr/lib/python2.7/getpass.py", line 83, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 118, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/usr/lib/python2.7/getpass.py", line 135, in _raw_input
    raise EOFError
EOFError
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by leonardofl** [comment]
Em cookbooks/jenkins/attributes/master.rb fiz a seguinte atribuição:

```
master['user'] = node['radar']['user']
master['group'] = node['radar']['user']
```

Mas parece que não funcionou, pois em /etc/default/jenkins  ainda temos:

```
JENKINS_USER=jenkins
JENKINS_GROUP=jenkins
```

E agora o build_radar falhou...
No log do jenkins:

```
OSError: [Errno 13] Permission denied: '/home/ubuntu/venv_jenkins/build'
```

Pois aparentemente ainda é o user jenkins q tá tentando acessar o virutal env.

Obs: também fiz a seguinte alteração nessa tentativa, no cookbooks/radar/recipes/jenkins.rb, para que o virtual env criado para o build fosse do usuário "normal" e não do usuário jenkins:

```
python_virtualenv "#{venv_folder}" do
  owner user
  group user
  action :create
end
```

**Comment by leonardofl** [comment]
Pelo oq pesquisei, parece que não é muito fácil (ou muito certo!) usar o jenkins com outro usuário (mesmo fora do contexto receitas Chef).
Mas agora que percebi que na verdade é o comando do Fabric que deveria estar sendo rodado com o usuário normal. No fabfile tem umas definições no "def localhost()", mas parece q não estão servindo... então podemos tentar colocar um "su user" no "def deploy()" ou colocar um "su user" lá na definição do job deploy_radar, quando ele manda rodar o fabric. 

fabfile: https://github.com/radar-parlamentar/implantacao/blob/master/cookbooks/radar/templates/default/fabfile.py.erb
job deploy radar: https://github.com/radar-parlamentar/implantacao/blob/master/cookbooks/radar/templates/default/jobDeployRadar_config.xml.erb

**Comment by leonardofl** [comment]
Parece que o problema era o jeito de o Fabric se conectar ao host. Fiz o Fabric usar o ssh com chave privada (que é como nos conectamos normalmente à VM) e aí o sudo funcionou sem pedir senha.
Mas daí pra resolver nessa linha, quem fosse executar a receita teria q colocar na VM a chave pra acessar a própria VM.
Isso tem algum ganho teórico se a gente considerar o ambiente de integração contínua separado do ambiente da aplicação, e que em nosso caso por "coincidência" os dois são os mesmos. Mas parece não valer a pena o trampo.
E nessa brincadeira, descobri como fazer pro usuário jenkins mudar pro usuário normal sem precisar de senha.
Então acho q vou na linha de fazer o usuário jenkins mudar pro usuário normal e executar o chef direto, e aí desencanar de usar o Fabric (uma peça a menos pra entender o esquema todo).

**Comment by leonardofl** [comment]
Obs: para que o usuário jenkins possa chavear para o usuário normal basta adicionar no `/etc/sudoers` a linha: `jenkins ALL=(ALL)       NOPASSWD: ALL`

**Comment by leonardofl** [comment]
Feito, Fabric removido, e receita radar::default sendo executada nos conformes.

373174d8b2c86622f8196d99c8c9261c842a04a5
c641faaa2586acfba0b18d295cafa6c50b5ffe3e
